/// Flutter icons TwitterIcon
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TwitterIcon
///      fonts:
///       - asset: fonts/TwitterIcon.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
///
///



import 'package:flutter/widgets.dart';

class YouTube {
  YouTube._();

  static const _kFontFam = 'YouTube';
  static const String? _kFontPkg = null;

  static const IconData youtube = IconData(0xf167, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class InstagramIcon {
  InstagramIcon._();

  static const _kFontFam = 'InstagramIcon';
  static const String? _kFontPkg = null;

  static const IconData instagram = IconData(0xf16d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class FacebookIcon {
  FacebookIcon._();

  static const _kFontFam = 'FacebookIcon';
  static const String? _kFontPkg = null;

  static const IconData facebook = IconData(0xf09a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class TwitterIcon {
  TwitterIcon._();

  static const _kFontFam = 'TwitterIcon';
  static const String? _kFontPkg = null;

  static const IconData twitter = IconData(0xf099, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
